// Code generated by controller-gen-compatible hand-written helpers; DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

func (in *BusinessWorkItem) DeepCopyInto(out *BusinessWorkItem) {
	*out = *in
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *BusinessWorkItem) DeepCopy() *BusinessWorkItem {
	if in == nil {
		return nil
	}
	out := new(BusinessWorkItem)
	in.DeepCopyInto(out)
	return out
}

func (in *BusinessWorkItem) DeepCopyObject() runtime.Object {
	return in.DeepCopy()
}

func (in *BusinessWorkItemList) DeepCopyInto(out *BusinessWorkItemList) {
	*out = *in
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]BusinessWorkItem, len(in.Items))
		for i := range in.Items {
			in.Items[i].DeepCopyInto(&out.Items[i])
		}
	}
}

func (in *BusinessWorkItemList) DeepCopy() *BusinessWorkItemList {
	if in == nil {
		return nil
	}
	out := new(BusinessWorkItemList)
	in.DeepCopyInto(out)
	return out
}

func (in *BusinessWorkItemList) DeepCopyObject() runtime.Object {
	return in.DeepCopy()
}

func (in *BusinessWorkItemSpec) DeepCopyInto(out *BusinessWorkItemSpec) {
	*out = *in
	in.Facts.DeepCopyInto(&out.Facts)
	in.Link.DeepCopyInto(&out.Link)
}

func (in *BusinessWorkItemStatus) DeepCopyInto(out *BusinessWorkItemStatus) {
	*out = *in
	in.Decision.DeepCopyInto(&out.Decision)
	if in.Decision.EvaluatedAt != nil {
		out.Decision.EvaluatedAt = in.Decision.EvaluatedAt.DeepCopy()
	}
	if in.History != nil {
		out.History = make([]HistoryEntry, len(in.History))
		for i := range in.History {
			in.History[i].DeepCopyInto(&out.History[i])
		}
	}
	if in.Conditions != nil {
		out.Conditions = make([]metav1.Condition, len(in.Conditions))
		for i := range in.Conditions {
			in.Conditions[i].DeepCopyInto(&out.Conditions[i])
		}
	}
}

func (in *BusinessFacts) DeepCopyInto(out *BusinessFacts) {
	*out = *in
	if in.SourceFacts != nil {
		out.SourceFacts = make(map[string]string, len(in.SourceFacts))
		for key, value := range in.SourceFacts {
			out.SourceFacts[key] = value
		}
	}
	if in.CostApproved != nil {
		out.CostApproved = new(bool)
		*out.CostApproved = *in.CostApproved
	}
}

func (in *JobLink) DeepCopyInto(out *JobLink) {
	*out = *in
}

func (in *DecisionStatus) DeepCopyInto(out *DecisionStatus) {
	*out = *in
}

func (in *HistoryEntry) DeepCopyInto(out *HistoryEntry) {
	*out = *in
}

func (in *LinkedWorkloadStatus) DeepCopyInto(out *LinkedWorkloadStatus) {
	*out = *in
}
